module Dir.Other_dir exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: dir/other_dir.proto

import Protobuf exposing (..)
import Dict exposing (Dict)
import Json.Decode as JD
import Json.Encode as JE


uselessDeclarationToPreventErrorDueToEmptyOutputFile = 42

requiredWithoutDefault : String -> JD.Decoder a -> JD.Decoder (a -> b) -> JD.Decoder b
requiredWithoutDefault name decoder d =
    field (JD.field name decoder) d

requiredFieldEncoderWithoutDefault : String -> (a -> JE.Value) -> a -> Maybe ( String, JE.Value )
requiredFieldEncoderWithoutDefault name encoder v =
    Just ( name, encoder v )


type alias OtherDir =
    { stringField : String -- 1
    }


otherDirDecoder : JD.Decoder OtherDir
otherDirDecoder =
    JD.lazy <| \_ -> decode OtherDir
        |> required "stringField" JD.string ""


otherDirEncoder : OtherDir -> JE.Value
otherDirEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "stringField" JE.string "" v.stringField)
        ]
