module Api exposing (..)
-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: forward.proto

import Forward
import Helpers.Api
import Helpers.Api.Result exposing (ApiResult)
import HubTran.Effect as Effect
import HubTran.Flash as Flash
import Json.Decode
import Json.Encode
import Pb


defaultServerErrorHandler : error -> Effect.Effect msg
defaultServerErrorHandler error =
    let
        _ =
            Debug.log "Unexpected Result" error
    in
    Effect.flash Flash.defaultServerErrorAlert


request : String -> value -> (value -> Json.Encode.Value) -> Json.Decode.Decoder a -> Effect.Effect (ApiResult String a)
request path value encoder decoder =
    Helpers.Api.post path
        (encoder value)
        decoder
        |> Forward.sendWithError identity



myServiceThisIsMyRpc : MyPackage.MyEntity -> Effect.Effect (ApiResult String MyPackage.MyChildEntity)
myServiceThisIsMyRpc p =
    request "/my_service/this_is_my_rpc"
        p
        MyPackage.myEntityEncoder
        MyPackage.myChildEntityDecoder

