module Api exposing (..)
-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: forward.proto

import Forward
import ForwardNew.PostRequestState as PostRequestState exposing (PostRequest)
import Helpers.Api
import HubTran.Effect as Effect
import HubTran.Flash as Flash
import Json.Decode
import Json.Encode
import Pb


defaultServerErrorHandler : error -> Effect.Effect msg
defaultServerErrorHandler error =
    let
        _ =
            Debug.log "Unexpected Result" error
    in
    Effect.flash Flash.defaultServerErrorAlert


request : String -> value -> (value -> Json.Encode.Value) -> Json.Decode.Decoder a -> PostRequest String a
request path value encoder decoder =
    Helpers.Api.post path
        (encoder value)
        decoder
        |> Forward.sendWithError identity
        |> PostRequestState.fromEffect


myServiceThisIsMyRpc : MyPackage.MyEntity -> PostRequest String MyPackage.MyChildEntity
myServiceThisIsMyRpc p =
    request "/my_service/this_is_my_rpc"
        p
        MyPackage.myEntityEncoder
        MyPackage.myChildEntityDecoder

