module Ids exposing (
     unpackImportedCarrierss, ImportedCarrierss(..)
    , unpackMyChildEntity, MyChildEntity(..)
    , unpackMyEntity, MyEntity(..)
    , unpackMyNewlyDefinedEntity, MyNewlyDefinedEntity(..)
    , unpackOverrideName, OverrideName(..)
    , unpackSelfReferencing, SelfReferencing(..)
    , unpackUnreferencedEntity, UnreferencedEntity(..)
    )

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: forward.proto


type ImportedCarrierss
    = ImportedCarrierss String

unpackImportedCarrierss : ImportedCarrierss -> String
unpackImportedCarrierss (ImportedCarrierss v) = v


type MyChildEntity
    = MyChildEntity String

unpackMyChildEntity : MyChildEntity -> String
unpackMyChildEntity (MyChildEntity v) = v


type MyEntity
    = MyEntity String

unpackMyEntity : MyEntity -> String
unpackMyEntity (MyEntity v) = v


type MyNewlyDefinedEntity
    = MyNewlyDefinedEntity String

unpackMyNewlyDefinedEntity : MyNewlyDefinedEntity -> String
unpackMyNewlyDefinedEntity (MyNewlyDefinedEntity v) = v


type OverrideName
    = OverrideName String

unpackOverrideName : OverrideName -> String
unpackOverrideName (OverrideName v) = v


type SelfReferencing
    = SelfReferencing String

unpackSelfReferencing : SelfReferencing -> String
unpackSelfReferencing (SelfReferencing v) = v


type UnreferencedEntity
    = UnreferencedEntity String

unpackUnreferencedEntity : UnreferencedEntity -> String
unpackUnreferencedEntity (UnreferencedEntity v) = v



