module Ids exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: forward.proto


type ImportedCarrierss
    = ImportedCarrierss String

importedCarrierssToString : ImportedCarrierss -> String
importedCarrierssToString (ImportedCarrierss v) = v


type MyChildEntity
    = MyChildEntity String

myChildEntityToString : MyChildEntity -> String
myChildEntityToString (MyChildEntity v) = v


type MyEntity
    = MyEntity String

myEntityToString : MyEntity -> String
myEntityToString (MyEntity v) = v


type MyNewlyDefinedEntity
    = MyNewlyDefinedEntity String

myNewlyDefinedEntityToString : MyNewlyDefinedEntity -> String
myNewlyDefinedEntityToString (MyNewlyDefinedEntity v) = v


type OverrideName
    = OverrideName String

overrideNameToString : OverrideName -> String
overrideNameToString (OverrideName v) = v


type SelfReferencing
    = SelfReferencing String

selfReferencingToString : SelfReferencing -> String
selfReferencingToString (SelfReferencing v) = v


type UnreferencedEntity
    = UnreferencedEntity String

unreferencedEntityToString : UnreferencedEntity -> String
unreferencedEntityToString (UnreferencedEntity v) = v



