#!/bin/bash

set -euo pipefail

readonly ROOT="$(git rev-parse --show-toplevel)"
readonly TEST_ROOT="${ROOT}/test-diffs"
readonly ELM_PLUGIN="${ROOT}/elm-project/elm-protobuf-test"

if [[ ! -f "${ELM_PLUGIN}" ]]; then
    echo "compiled test plugin required"
    exit 1
fi

for TEST in "${TEST_ROOT}"/*/; do
    TEST="${TEST%*/}" # strip  trailing "/"

    INPUT_DIR="${TEST}/input"
    OUTPUT_DIR="${TEST}/actual_output"
    EXPECTED_DIR="${TEST}/expected_output"

    mkdir -p "${OUTPUT_DIR}"

    if [[ $TEST == *forward ]] # * is used for pattern matching
    then
      protoc \
          --proto_path="${INPUT_DIR}" \
          --plugin=protoc-gen-elm="${ELM_PLUGIN}" \
          --elm_out="${OUTPUT_DIR}" \
          --elm_opt="remove-deprecated,generate-forward-cache,generate-forward-ids,generate-forward-graph" \
          --experimental_allow_proto3_optional \
          "${INPUT_DIR}"/*.proto
    else
      protoc \
          --proto_path="${INPUT_DIR}" \
          --plugin=protoc-gen-elm="${ELM_PLUGIN}" \
          --elm_out="${OUTPUT_DIR}" \
          --elm_opt=remove-deprecated \
          --experimental_allow_proto3_optional \
          "${INPUT_DIR}"/*.proto
    fi

    if ! DIFF_OUTPUT=$(diff -y -r "${EXPECTED_DIR}" "${OUTPUT_DIR}") ; then
        echo "${DIFF_OUTPUT}"
        echo "Detected difference in ${INPUT_DIR}"
        exit 1
    fi
done

protoc \
    --proto_path=../wallet/lib/frontend/ \
    --plugin=protoc-gen-elm="${ELM_PLUGIN}" \
    --elm_out=..//wallet/client/elm/app/src/ \
    --elm_opt="remove-deprecated,generate-forward-cache,generate-forward-ids,generate-forward-graph" \
    --experimental_allow_proto3_optional \
    frontend.proto

echo "All tests pass"
