module DomainNew.Graph exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: forward.proto


import ForwardNew.Interface.Cache as Cache
import ForwardNew.Lookup as Lookup exposing (Lookup)
import Ids
import Json.Decode as Decode
import LocalExtra.Lookup as LookupExtra
import MyPackage

allDecoders : List Lookup.DecoderConfig
allDecoders = [
     Lookup.toDecoderConfig mySingleton 
    , Lookup.toDecoderConfig importedCarrierss 
    , Lookup.toDecoderConfig myEntity 
    , Lookup.toDecoderConfig myChildEntity 
    , Lookup.toDecoderConfig unreferencedEntity 
    , Lookup.toDecoderConfig selfReferencing 
    , Lookup.toDecoderConfig overrideName 
    , Lookup.toDecoderConfig messageWithForeignKeyId 
    ]


mySingleton : Lookup () Pb.MySingleton
mySingleton =
    Lookup.defineNode
        { entrypoint = "mySingleton"
        , parameters = Lookup.noParameters
        , decoder = Pb.mySingletonDecoder
        , cacheKey = Cache.mySingleton
        }

importedCarrierss : Lookup Ids.ImportedCarrierss Pb.ImportedCarrierss
importedCarrierss =
    Lookup.defineNode
        { entrypoint = "importedCarrierss"
        , parameters = LookupExtra.idParam (\(Ids.ImportedCarrierss id) -> id)
        , decoder = Pb.importedCarrierssDecoder
        , cacheKey = Cache.importedCarrierss
        }

myEntity : Lookup Ids.MyEntity Pb.MyEntity
myEntity =
    Lookup.defineNode
        { entrypoint = "myEntity"
        , parameters = LookupExtra.idParam (\(Ids.MyEntity id) -> id)
        , decoder = Pb.myEntityDecoder
        , cacheKey = Cache.myEntity
        }

myChildEntity : Lookup Ids.MyChildEntity Pb.MyChildEntity
myChildEntity =
    Lookup.defineNode
        { entrypoint = "myChildEntity"
        , parameters = LookupExtra.idParam (\(Ids.MyChildEntity id) -> id)
        , decoder = Pb.myChildEntityDecoder
        , cacheKey = Cache.myChildEntity
        }

unreferencedEntity : Lookup Ids.UnreferencedEntity Pb.UnreferencedEntity
unreferencedEntity =
    Lookup.defineNode
        { entrypoint = "unreferencedEntity"
        , parameters = LookupExtra.idParam (\(Ids.UnreferencedEntity id) -> id)
        , decoder = Pb.unreferencedEntityDecoder
        , cacheKey = Cache.unreferencedEntity
        }

selfReferencing : Lookup Ids.SelfReferencing Pb.SelfReferencing
selfReferencing =
    Lookup.defineNode
        { entrypoint = "selfReferencing"
        , parameters = LookupExtra.idParam (\(Ids.SelfReferencing id) -> id)
        , decoder = Pb.selfReferencingDecoder
        , cacheKey = Cache.selfReferencing
        }

overrideName : Lookup Ids.OverrideName Pb.OverrideName
overrideName =
    Lookup.defineNode
        { entrypoint = "overrideName"
        , parameters = LookupExtra.idParam (\(Ids.OverrideName id) -> id)
        , decoder = Pb.overrideNameDecoder
        , cacheKey = Cache.overrideName
        }

messageWithForeignKeyId : Lookup Ids.MyNewlyDefinedEntity Pb.MessageWithForeignKeyId
messageWithForeignKeyId =
    Lookup.defineNode
        { entrypoint = "messageWithForeignKeyId"
        , parameters = LookupExtra.idParam (\(Ids.MyNewlyDefinedEntity id) -> id)
        , decoder = Pb.messageWithForeignKeyIdDecoder
        , cacheKey = Cache.messageWithForeignKeyId
        }

