module ForwardNew.Interface.Cache exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: forward.proto

import ForwardNew.CacheKey exposing (CacheKey, cacheKey)
import ForwardNew.EntrypointCache as EntrypointCache exposing (EntrypointCache)
import Ids
import Pb

type alias Cache = { 
	  myEntity : EntrypointCache Pb.MyEntity  
	,  myChildEntity : EntrypointCache Pb.MyChildEntity  
	,  unreferencedEntity : EntrypointCache Pb.UnreferencedEntity  
	,  selfReferencing : EntrypointCache Pb.SelfReferencing  
	,  overrideName : EntrypointCache Pb.OverrideName  
	,  list_idsMyEntity : EntrypointCache (List Ids.MyEntity)  
	,  list_idsMyChildEntity : EntrypointCache (List Ids.MyChildEntity)  
	,  list_idsUnreferencedEntity : EntrypointCache (List Ids.UnreferencedEntity)  
	,  list_idsSelfReferencing : EntrypointCache (List Ids.SelfReferencing)  
	,  list_idsOverrideName : EntrypointCache (List Ids.OverrideName)  
}

empty : Cache
empty = { 
	 myEntity = EntrypointCache.empty 
	, myChildEntity = EntrypointCache.empty 
	, unreferencedEntity = EntrypointCache.empty 
	, selfReferencing = EntrypointCache.empty 
	, overrideName = EntrypointCache.empty 
	, list_idsMyEntity = EntrypointCache.empty 
	, list_idsMyChildEntity = EntrypointCache.empty 
	, list_idsUnreferencedEntity = EntrypointCache.empty 
	, list_idsSelfReferencing = EntrypointCache.empty 
	, list_idsOverrideName = EntrypointCache.empty 
}



myEntity : CacheKey Cache Pb.MyEntity
myEntity =
    cacheKey .myEntity (\e c -> { c | myEntity = e })



myChildEntity : CacheKey Cache Pb.MyChildEntity
myChildEntity =
    cacheKey .myChildEntity (\e c -> { c | myChildEntity = e })



unreferencedEntity : CacheKey Cache Pb.UnreferencedEntity
unreferencedEntity =
    cacheKey .unreferencedEntity (\e c -> { c | unreferencedEntity = e })



selfReferencing : CacheKey Cache Pb.SelfReferencing
selfReferencing =
    cacheKey .selfReferencing (\e c -> { c | selfReferencing = e })



overrideName : CacheKey Cache Pb.OverrideName
overrideName =
    cacheKey .overrideName (\e c -> { c | overrideName = e })



list_idsMyEntity : CacheKey Cache (List Ids.MyEntity)
list_idsMyEntity =
    cacheKey .list_idsMyEntity (\e c -> { c | list_idsMyEntity = e })



list_idsMyChildEntity : CacheKey Cache (List Ids.MyChildEntity)
list_idsMyChildEntity =
    cacheKey .list_idsMyChildEntity (\e c -> { c | list_idsMyChildEntity = e })



list_idsUnreferencedEntity : CacheKey Cache (List Ids.UnreferencedEntity)
list_idsUnreferencedEntity =
    cacheKey .list_idsUnreferencedEntity (\e c -> { c | list_idsUnreferencedEntity = e })



list_idsSelfReferencing : CacheKey Cache (List Ids.SelfReferencing)
list_idsSelfReferencing =
    cacheKey .list_idsSelfReferencing (\e c -> { c | list_idsSelfReferencing = e })



list_idsOverrideName : CacheKey Cache (List Ids.OverrideName)
list_idsOverrideName =
    cacheKey .list_idsOverrideName (\e c -> { c | list_idsOverrideName = e })


