module ForwardNew.Interface.Cache exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: forward.proto

import ForwardNew.CacheKey exposing (CacheKey, cacheKey)
import ForwardNew.EntrypointCache as EntrypointCache exposing (EntrypointCache)
import Ids
import MyPackage

type alias Cache = { 
      mySingleton : EntrypointCache Pb.MySingleton  
    ,  importedCarrierss : EntrypointCache Pb.ImportedCarrierss  
    ,  myEntity : EntrypointCache Pb.MyEntity  
    ,  myChildEntity : EntrypointCache Pb.MyChildEntity  
    ,  unreferencedEntity : EntrypointCache Pb.UnreferencedEntity  
    ,  selfReferencing : EntrypointCache Pb.SelfReferencing  
    ,  overrideName : EntrypointCache Pb.OverrideName  
    ,  messageWithForeignKeyId : EntrypointCache Pb.MessageWithForeignKeyId  
    ,  list_idsImportedCarrierss : EntrypointCache (List Ids.ImportedCarrierss)  
    ,  list_idsMyChildEntity : EntrypointCache (List Ids.MyChildEntity)  
    ,  list_idsMyEntity : EntrypointCache (List Ids.MyEntity)  
    ,  list_idsMyNewlyDefinedEntity : EntrypointCache (List Ids.MyNewlyDefinedEntity)  
    ,  list_idsOverrideName : EntrypointCache (List Ids.OverrideName)  
    ,  list_idsSelfReferencing : EntrypointCache (List Ids.SelfReferencing)  
    ,  list_idsUnreferencedEntity : EntrypointCache (List Ids.UnreferencedEntity)  
    }

empty : Cache
empty = { 
     mySingleton = EntrypointCache.empty 
    , importedCarrierss = EntrypointCache.empty 
    , myEntity = EntrypointCache.empty 
    , myChildEntity = EntrypointCache.empty 
    , unreferencedEntity = EntrypointCache.empty 
    , selfReferencing = EntrypointCache.empty 
    , overrideName = EntrypointCache.empty 
    , messageWithForeignKeyId = EntrypointCache.empty 
    , list_idsImportedCarrierss = EntrypointCache.empty 
    , list_idsMyChildEntity = EntrypointCache.empty 
    , list_idsMyEntity = EntrypointCache.empty 
    , list_idsMyNewlyDefinedEntity = EntrypointCache.empty 
    , list_idsOverrideName = EntrypointCache.empty 
    , list_idsSelfReferencing = EntrypointCache.empty 
    , list_idsUnreferencedEntity = EntrypointCache.empty 
    }



mySingleton : CacheKey Cache Pb.MySingleton
mySingleton =
    cacheKey .mySingleton (\e c -> { c | mySingleton = e })



importedCarrierss : CacheKey Cache Pb.ImportedCarrierss
importedCarrierss =
    cacheKey .importedCarrierss (\e c -> { c | importedCarrierss = e })



myEntity : CacheKey Cache Pb.MyEntity
myEntity =
    cacheKey .myEntity (\e c -> { c | myEntity = e })



myChildEntity : CacheKey Cache Pb.MyChildEntity
myChildEntity =
    cacheKey .myChildEntity (\e c -> { c | myChildEntity = e })



unreferencedEntity : CacheKey Cache Pb.UnreferencedEntity
unreferencedEntity =
    cacheKey .unreferencedEntity (\e c -> { c | unreferencedEntity = e })



selfReferencing : CacheKey Cache Pb.SelfReferencing
selfReferencing =
    cacheKey .selfReferencing (\e c -> { c | selfReferencing = e })



overrideName : CacheKey Cache Pb.OverrideName
overrideName =
    cacheKey .overrideName (\e c -> { c | overrideName = e })



messageWithForeignKeyId : CacheKey Cache Pb.MessageWithForeignKeyId
messageWithForeignKeyId =
    cacheKey .messageWithForeignKeyId (\e c -> { c | messageWithForeignKeyId = e })



list_idsImportedCarrierss : CacheKey Cache (List Ids.ImportedCarrierss)
list_idsImportedCarrierss =
    cacheKey .list_idsImportedCarrierss (\e c -> { c | list_idsImportedCarrierss = e })



list_idsMyChildEntity : CacheKey Cache (List Ids.MyChildEntity)
list_idsMyChildEntity =
    cacheKey .list_idsMyChildEntity (\e c -> { c | list_idsMyChildEntity = e })



list_idsMyEntity : CacheKey Cache (List Ids.MyEntity)
list_idsMyEntity =
    cacheKey .list_idsMyEntity (\e c -> { c | list_idsMyEntity = e })



list_idsMyNewlyDefinedEntity : CacheKey Cache (List Ids.MyNewlyDefinedEntity)
list_idsMyNewlyDefinedEntity =
    cacheKey .list_idsMyNewlyDefinedEntity (\e c -> { c | list_idsMyNewlyDefinedEntity = e })



list_idsOverrideName : CacheKey Cache (List Ids.OverrideName)
list_idsOverrideName =
    cacheKey .list_idsOverrideName (\e c -> { c | list_idsOverrideName = e })



list_idsSelfReferencing : CacheKey Cache (List Ids.SelfReferencing)
list_idsSelfReferencing =
    cacheKey .list_idsSelfReferencing (\e c -> { c | list_idsSelfReferencing = e })



list_idsUnreferencedEntity : CacheKey Cache (List Ids.UnreferencedEntity)
list_idsUnreferencedEntity =
    cacheKey .list_idsUnreferencedEntity (\e c -> { c | list_idsUnreferencedEntity = e })


