module Ids exposing (
         MyEntity(..)
        , MyChildEntity(..)
        , UnreferencedEntity(..)
        , SelfReferencing(..)
        , OverrideName(..)
)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: forward.proto


type MyEntity
    = MyEntity String

type MyChildEntity
    = MyChildEntity String

type UnreferencedEntity
    = UnreferencedEntity String

type SelfReferencing
    = SelfReferencing String

type OverrideName
    = OverrideName String


